version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"   # Web UI
      - "9000:9000"   # HDFS
    environment:
      - CLUSTER_NAME=test-hadoop
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=test-hadoop
      - NAMENODE_HOST=namenode
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9864:9864"   # Web UI
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop

  spark:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: spark
    depends_on:
      - namenode
      - datanode
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./app:/home/jovyan/app
      - ./data:/home/jovyan/data
      - ./logs:/logs
    command: sleep infinity
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
    driver: bridge
